### ISSUE TITLE
Possibility to add middle points to the route

### ISSUE THREAD

**Issue by serge1peshcoff** [NoryDev/hitchspots#18]
It would be nice to specify not only the start and finish point, but also the points the route should go through. For instance, a week ago I needed to hitchhike from Krakow to Voronezh through Lviv, Kyiv and Kharkiv, and the default route wasn't going through Kharkiv, so I needed to download 3 KML files (Krakow-Kyiv, Kyiv-Kharkiv, Kharkiv-Voronezh) to see all the points.

I think it'd be a cool feature and this is the thing I want to implement, but I want to know your opinion, what do you think @NoryDev ?

**Comment by NoryDev** [comment]
@serge1peshcoff I see your point.

It's a good feature, the important thing to me is that the interface remains super easy to use. If you want to do a proposal, go ahead!

**Comment by serge1peshcoff** [comment]
@NoryDev I will make a PR on that in a few days when I'll have free time, should be not that hard to implement.
