### ISSUE TITLE
Change mentions of Maps.ME to Organic Maps

### ISSUE THREAD

**Issue by pastk** [norydev/hitchspots#53]
Organic Maps https://github.com/organicmaps/organicmaps is an open-source fork of Maps.ME
- no advertising, no trackers or data collection - privacy focused
- completely run by volunteers

Unfortunately, after the last acquisition Maps.me changed its direction, its not open-source anymore and is more monetisation-focused.

So I think Organic Maps is a better match to hitch-hiking and open source communities nowadays, hence I suggest to replace all mentions of Maps.me in Hitchspots to Organic Maps (generated KMLs are imported into OM just fine). Or at least mention both OM and MM (as still a lot of people use the latter and don't know about existence of OM).

**Comment by norydev** [comment]
Excellent idea, I have been using Organic maps myself for more than a year and very happy with it. Feel free to open a PR (Or I'll do it when I find time)

**Comment by norydev** [comment]
@pastk I (finally) did the update in #57,
closing this one.

**Comment by pastk** [comment]
Great, thanks a lot!
